In [1]:
import statsmodels
import numpy as np
import matplotlib.pylab as plt

In [7]:
array = np.ones((100,50))
array.shape

(100, 50)

In [8]:
array1 = np.zeros((100,50))
array.shape

(100, 50)

In [10]:
array_combined = np.concatenate((array, array1))
array_combined

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
array3 = (array + array1)
array3

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [24]:
mean = [0, 0]
cov = [[1, 0], [0, 100]]
array4 = np.random.multivariate_normal(mean, cov, (20, 40))
array5 = np.random.multivariate_normal(mean, cov, (20, 40))

In [23]:
array6 = array4 * array5
array6

array([[[-5.34336591e-01,  1.40015712e+02],
        [ 7.81886668e-01, -6.89520682e+01],
        [-2.54922813e-03,  5.33343898e+01],
        ...,
        [ 1.16490378e+00, -2.22397077e+01],
        [ 3.12723050e-02, -4.02170607e+01],
        [ 3.78495305e-02, -5.89672812e+01]],

       [[-2.27288143e-01, -4.10208155e+00],
        [ 1.75055477e+00, -1.16489009e+01],
        [ 2.53062011e+00,  7.97090471e+01],
        ...,
        [-5.75334054e+00,  8.29792024e+00],
        [ 2.39192198e+00, -3.78022771e+01],
        [-7.62518231e-01,  6.37455419e+01]],

       [[-3.02118933e-01, -1.10796830e+00],
        [-7.83132751e-01,  1.12347356e+02],
        [ 5.85964325e-01, -1.32118044e+01],
        ...,
        [-2.87003382e-01,  3.93705450e+01],
        [-1.83312937e+00, -1.54665240e+02],
        [-2.47861392e-01,  1.50611394e+01]],

       ...,

       [[-2.55286460e-01, -1.80542006e+02],
        [ 8.55557552e-02,  2.01644361e+01],
        [ 2.43996313e-02, -5.37942979e+00],
        ...,
     

In [ ]:
np.mat.